projekat1/fudbaleri/urls.py
from django.urls import path
from . import views


app_name: 'fudbaleri'
urlpatterns = [
    path('', views.index, name='index'),
    path('fudbaleri/', views.fudbaleri, name='fudbaleri'),
    path('fudbaleri/<int:id>/', views.fudbaler, name='fudbaler'),
    path('fudbaler/edit/<int:id>/', views.edit, name='edit'),
    path('fudbaler/new/', views.new, name='new'),
    path('registration/', views.registration, name='registration'),
    path('delete/<str:pk>/', views.delete, name='delete')
]

projekat1/projekat1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('fudbaleri.urls')),

]

projekat1/fudbaleri/models.py
from django.db import models
from django.contrib.auth.models import User


class Fudbaler(models.Model):
    ime = models.CharField(max_length=30)
    prezime = models.CharField(max_length=30)
    godine = models.IntegerField(max_length=45)
    brojNaDresu = models.IntegerField(max_length=99)
    tim = models.CharField(max_length=30)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.prezime

    def is_popular(self):
        return self.godine > 5

projekat1/fudbaleri/forms.py
from django.forms import ModelForm
from .models import Fudbaler
from django.contrib.auth.models import User


class FudbalerForm(ModelForm):
    class Meta:
        model = Fudbaler
        fields = ['ime', 'prezime', 'godine', 'brojNaDresu', 'tim']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

projekat1/fudbaleri/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from .models import Fudbaler
from .forms import FudbalerForm, UserForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate


def index(req):
    if not req.user.is_authenticated:
        return render(req, 'index.html', {'page_title': 'Vezbe 13'})
    else:
        return redirect('fudbaleri')


@login_required
def fudbaleri(req):
    tmp = Fudbaler.objects.all()
    return render(req, 'fudbaleri.html', {'fudbaleri': tmp})


@login_required
def fudbaler(req, id):
    tmp = get_object_or_404(Fudbaler, id=id)
    return render(req, 'fudbaler.html', {'fudbaler': tmp, 'page_title': tmp.ime})


@permission_required('change_fudbaler')
def edit(req, id):
    if req.method == 'POST':
        form = FudbalerForm(req.POST)

        if form.is_valid():
            a = Fudbaler.objects.get(id=id)
            a.ime = form.cleaned_data['ime']
            a.prezime = form.cleaned_data['prezime']
            a.godine = form.cleaned_data['godine']
            a.brojNaDresu = form.cleaned_data['brojNaDresu']
            a.tim = form.cleaned_data['tim']
            a.save()
            return redirect('fudbaleri')
        else:
            return render(req, 'edit.html', {'form': form, 'id': id})
    else:
        a = Fudbaler.objects.get(id=id)
        form = FudbalerForm(instance=a)
        return render(req, 'edit.html', {'form': form, 'id': id})


@permission_required('fudbaler')
def new(req):
    if req.method == 'POST':
        print("prvoif")
        form = FudbalerForm(req.POST)

        if form.is_valid():
            print("drugoif")
            a = Fudbaler(ime=form.cleaned_data['ime'], prezime=form.cleaned_data['prezime'],
                         godine=form.cleaned_data['godine'],
                         brojNaDresu=form.cleaned_data['brojNaDresu'], tim=form.cleaned_data['tim'],
                         owner=req.user)
            a.save()
            return redirect('fudbaleri')
        else:
            print("prvoelse")
            return render(req, 'new.html', {'form': form})
    else:
        form = FudbalerForm()
        print("drugoelse")
        return render(req, 'new.html', {'form': form})


def registration(req):
    if req.method == 'POST':
        form = UserCreationForm(req.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(req, user)
            return redirect('fudbaleri')
    else:
        form = UserCreationForm()
    return render(req, 'registration.html', {'form': form})


def delete(req, pk):
    fudbaler = Fudbaler.objects.get(id=pk)
    if req.method == "POST":
        fudbaler.delete()
        return redirect('fudbaleri')

    context = {'item': fudbaler}
    return render(req, 'delete.html', context)

projekat1/fudbaleri/templates/delete.html
{%  extends 'master.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'delete' item.id  %}" method="POST">

				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'fudbaleri' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

projekat1/fudbaleri/templates/edit.html
{% extends 'master.html' %}

{% block title %}
    Edit fudbaler
{% endblock %}

{% block content %}

     <form method="post" action="{% url 'edit' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.ime.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.ime.name }}" value="{{ form.ime.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.prezime.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.prezime.name }}" value="{{ form.prezime.value }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

         <div class="form-group">
            <label for="{{ form.godine.id_for_label }}">{{ form.godine.label_tag }}</label>
            <input type="number" max="45" class="form-control" id="{{ form.godine.id_for_label }}" name="{{ form.godine.name }}" value="{{ form.godine.value }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

         <div class="form-group">
            <label for="{{ form.brojNaDresu.id_for_label }}">{{ form.brojNaDresu.label_tag }}</label>
            <input type="number" max="99" class="form-control" id="{{ form.brojNaDresu.id_for_label }}" name="{{ form.brojNaDresu.name }}" value="{{ form.brojNaDresu.value }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

         <div class="form-group">
            <label for="{{ form.tim.id_for_label }}">{{ form.tim.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.tim.id_for_label }}" name="{{ form.tim.name }}" value="{{ form.tim.value }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>

{% endblock %}

projekat1/fudbaleri/templates/fudbaler.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ fudbaler.ime }}
                {% if perms.change_fudbaler %}
                    <a href="{% url 'edit' fudbaler.id %}">
                        <span class="badge badge-primary">Edit</span>
                    </a>
                {% endif %}
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ fudbaler.prezime }}</p>
                <footer class="blockquote-footer">
                    Author:
                    <cite title="Source Title">
                        {{ fudbaler.owner.username }}
                    </cite>
                </footer>
            </blockquote>
        </div>
    </div>

{% endblock %}

projekat1/fudbaleri/templates/fudbaleri.html
{%  extends 'master.html' %}

{% block ime %}
    fudbaleri
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for fudbaler in fudbaleri %}
            <a class="list-group-item list-group-item-action" href="{% url 'fudbaler' fudbaler.id %}">
                {{ fudbaler.ime }}
            </a>
        {% endfor %}
    </div>
{% endblock %}

projekat1/fudbaleri/templates/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
{% endblock %}

projekat1/fudbaleri/templates/new.html
{% extends 'master.html' %}

{% block title %}
    New Fudbaler
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'new' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}"> {{form.ime.label_tag}}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.ime.name }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.prezime.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.prezime.name }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
         <div class="form-group">
            <label for="{{ form.godine.id_for_label }}">{{ form.godine.label_tag }}</label>
            <input type="number" max="45" class="form-control" id="{{ form.godine.id_for_label }}" name="{{ form.godine.name }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
         <div class="form-group">
            <label for="{{ form.brojNaDresu.id_for_label }}">{{ form.brojNaDresu.label_tag }}</label>
            <input type="number" max="99" class="form-control" id="{{ form.brojNaDresu.id_for_label }}" name="{{ form.brojNaDresu.name }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
         <div class="form-group">
            <label for="{{ form.tim.id_for_label }}">{{ form.tim.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.tim.id_for_label }}" name="{{ form.tim.name }}">
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>


        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

projekat1/fudbaleri/templates/registration.html
{% extends 'master.html' %}

{% block title %}
 New User
{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post" action="{% url 'registration' %}">
        {% csrf_token %}
       {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}

        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
{% endblock %}

projekat1/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'fudbaleri' %}">
     <!--   <img src="{% static 'img/rocket.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
-->
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.fudbaleri.add_fudbaler %}
                <a class="nav-link disabled" href="{% url 'new' %}">New fudbaler</a>
            {% else %}
                <a class="nav-link" href="{% url 'new' %}">New fudbaler</a>
            {% endif %}
        </li>
    </ul>
    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% endif %}

</nav>

projekat1/templates/master.html
{% load static %}


<!DOCTYPE html>


<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
           <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>